//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by editor.rc
//
#define IDD_MAINFORM_DIALOG             2004
#define IDD_RENDERVIEW_DIALOG           2005
#define IDD_HELPDIALOG_DIALOG           2006
#define IDR_MAINMENU                    2009
#define IDB_WORLD                       2014
#define IDB_CLUMP                       2015
#define IDB_FRAME                       2016
#define IDB_ATOMIC                      2017
#define IDB_GEOMETRY                    2018
#define IDB_SHADER                      2019
#define IDD_SHADER_EDITOR               2020
#define IDB_HINT1                       2029
#define IDD_TEXTURE_CHOOSER             2041
#define IDD_EFFECT_EDITOR               2042
#define IDD_ENGINE_INFO                 2043
#define IDD_GEOMETRY_EDITOR             2044
#define IDB_LIGHT                       2047
#define IDD_BSP_EDITOR                  2049
#define IDD_LIGHT_EDITOR                2050
#define IDD_DETAILS_GENERATOR           2051
#define IDC_COMMAND                     2082
#define IDC_CONSOLE                     2083
#define IDC_SHELF                       2084
#define IDC_ASSETGRAPH                  2085
#define IDC_FLAG_CULLING                2126
#define IDC_FLAG_COLLISION              2127
#define IDC_FLAG_ALPHA_BLENDING         2128
#define IDC_FLAG_ALPHA_TESTING          2129
#define IDC_FLAG_RESERVED1              2135
#define IDC_FLAG_RESERVED2              2136
#define IDC_ALPHA_BLENDING_SRC          2137
#define IDC_ALPHA_BLENDING_OP           2138
#define IDC_ALPHA_BLENDING_DST          2139
#define IDC_ALPHA_TESTING_FUNCT         2140
#define IDC_ALPHA_TESTING_REF           2141
#define IDC_DIFFUSE_R                   2143
#define IDC_DIFFUSE_G                   2144
#define IDC_DIFFUSE_B                   2145
#define IDC_DIFFUSE_A                   2146
#define IDC_SPECULAR_R                  2147
#define IDC_SPECULAR_G                  2148
#define IDC_SPECULAR_B                  2149
#define IDC_DIFFUSE_BTN                 2150
#define IDC_SPECULAR_A                  2151
#define IDC_SPECULAR_BTN                2152
#define IDC_SPECULAR_POWER              2153
#define IDC_RADIUS                      2153
#define IDC_LAYER_0_UVID                2154
#define IDC_LAYER_0_BLENDING            2155
#define IDC_LAYER_0_CONSTANT_R          2156
#define IDC_LAYER_0_CONSTANT_G          2157
#define IDC_ATTENUATION_0               2157
#define IDC_LAYER_0_CONSTANT_B          2158
#define IDC_ATTENUATION_1               2158
#define IDC_LAYER_0_CONSTANT_A          2159
#define IDC_ATTENUATION_2               2159
#define IDC_LAYER_0_CONSTANT_BTN        2160
#define IDC_THETA                       2160
#define IDC_LAYER_1_UVID                2161
#define IDC_ATTENUATION_4               2161
#define IDC_PHI                         2161
#define IDC_LAYER_0_TEXTURE_BTN         2162
#define IDC_LAYER_1_TEXTURE_BTN         2163
#define IDC_LAYER_1_BLENDING            2164
#define IDC_LAYER_1_CONSTANT_R          2165
#define IDC_LAYER_1_CONSTANT_G          2166
#define IDC_LAYER_1_CONSTANT_B          2167
#define IDC_LAYER_1_CONSTANT_A          2168
#define IDC_LAYER_1_CONSTANT_BTN        2169
#define IDC_ALPHA_TESTING_REF2          2170
#define IDC_LAYER_2_TEXTURE_BTN         2178
#define IDC_LAYER_2_UVID                2179
#define IDC_LAYER_2_BLENDING            2180
#define IDC_LAYER_2_CONSTANT_R          2181
#define IDC_LAYER_2_CONSTANT_G          2182
#define IDC_LAYER_2_CONSTANT_B          2183
#define IDC_LAYER_2_CONSTANT_A          2184
#define IDC_LAYER_2_CONSTANT_BTN        2185
#define IDC_LAYER_3_TEXTURE_BTN         2186
#define IDC_LAYER_3_UVID                2187
#define IDC_LAYER_3_BLENDING            2188
#define IDC_LAYER_3_CONSTANT_R          2189
#define IDC_LAYER_3_CONSTANT_G          2190
#define IDC_LAYER_3_CONSTANT_B          2191
#define IDC_LAYER_3_CONSTANT_A          2192
#define IDC_LAYER_3_CONSTANT_BTN        2193
#define IDC_EFFECT                      2194
#define IDC_NORMAL_MAP_BTN              2196
#define IDC_NORMAL_MAP_UVID             2197
#define IDC_ENV_MAP_BTN                 2198
#define IDC_TROUBLEDESC                 2201
#define IDC_COMBO1                      2202
#define IDC_BUTTON1                     2203
#define IDC_MAGFILTER                   2204
#define IDC_BUTTON2                     2204
#define IDC_ANISOTROPY                  2205
#define IDC_BUTTON3                     2205
#define IDC_MIPMAPLODBIAS               2206
#define IDC_MINFILTER                   2207
#define IDC_OK_BUTTON                   2207
#define IDC_MIPFILTER                   2208
#define IDC_BSP_TOTAL                   2208
#define IDC_BSP_RENDERED                2209
#define IDC_UADDRESSING                 2209
#define IDC_FPS                         2210
#define IDC_VADDRESSING                 2210
#define IDC_ATOMICS_RENDERED            2211
#define IDC_ATOMICS_RENDERED2           2212
#define IDC_ALPHA_RENDERED              2212
#define IDC_SHADER_CACHE_HITS           2213
#define IDC_R                           2215
#define IDC_G                           2216
#define IDC_B                           2217
#define IDC_A                           2218
#define IDC_EFFECTNAME                  2219
#define IDC_LIST1                       2220
#define IDC_ARGLIST                     2220
#define IDC_FOG_R                       2222
#define IDC_FOG_G                       2223
#define IDC_FOG_B                       2224
#define IDC_FOG_A                       2225
#define IDC_FOG_START                   2226
#define IDC_FOG_END                     2227
#define IDC_FOG_DENSITY                 2228
#define IDC_FOG_TYPE                    2229
#define IDC_ATOMIC_NAME                 2232
#define IDC_GEOMETRY_NAME               2233
#define IDC_OUTPUT_CLUMP_NAME           2234
#define IDC_GROUP_SPHERE                2235
#define IDC_PARTICLE_DENSITY            2237
#define IDC_CANCEL_BUTTON               2238
#define IDC_DETAIL_LIST                 2239
#define IDC_DETAIL_CLASS                2240
#define IDC_LIGHTSET                    2242
#define ID_ASSET_OPEN                   32787
#define ID_ASSET_IMPORT                 32788
#define ID_ASSET_SAVE                   32789
#define ID_HELP_EDITORHELP              32790
#define ID_WINDOW_ENGINEINFO            32791
#define ID_CLUMP_PANALPHA               32792
#define ID_CLUMP_HIDEALLATOMICS         32793
#define ID_ANIMATION_ANIMATIONSPEED     32794
#define ID_ANIMATIONSPEED_X1            32795
#define ID_ANIMATIONSPEED_0             32796
#define ID_ANIMATIONSPEED_1             32797
#define ID_ANIMATION_RESETANIMATION     32798
#define ID_ANIMATION_ANIMATIONSPPED     32799
#define ID_SPEED_1X                     32800
#define ID_SPEED_0                      32801
#define ID_SPEED_1                      32802
#define ID_GENERATOR_GEOMETRYDETAILS    32803
#define ID_CLUMP_HIDESELECTEDATOMIC     32804
#define ID_CLUMP_FORCEPRELIGHT          32805
#define ID_ENABLE_ALPHA_TREE            32809
#define ID_ENABLE_ALPHA_BANISTER        32810
#define ID_ENABLE_NO_CULL               32811
#define ID_TOOLS_CREATEBUMPMAP          32812
#define ID_TOOLS_NORMALMAPFROMTEXTURE   32813
#define ID_MATERIAL_SETNUMBEROFTEXTURELAYERS 32814
#define ID_SETNUMBEROFTEXTURELAYERS_0LAYERS 32815
#define ID_SETNUMBEROFTEXTURELAYERS_1LAYER 32816
#define ID_SETNUMBEROFTEXTURELAYERS_2LAYERS 32817
#define ID_SETNUMBEROFTEXTURELAYERS_3LAYERS 32818
#define ID_SETNUMBEROFTEXTURELAYERS_0   32819
#define ID_SETNUMBEROFTEXTURELAYERS_1   32820
#define ID_SETNUMBEROFTEXTURELAYERS_2   32821
#define ID_SETNUMBEROFTEXTURELAYERS_3   32822
#define ID_SETNUMBEROFTEXTURELAYERS_4   32823
#define ID_TOOLS_CALCULATELIGHTMAPS     32824
#define ID_TOOLS_CALCULATELIGHTMAPS32825 32825
#define ID_CLUMP_DELETE                 32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2052
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         2243
#define _APS_NEXT_SYMED_VALUE           2007
#endif
#endif
